name: Check
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - "**"
env:
  NODE_OPTIONS: --max_old_space_size=10240
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install front-end dependencies
        run: pnpm install
      - name: Build front-end assets
        run: pnpm run build
      - name: Check
        run: pnpm run lint
