name: Publish
on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/*.gitignore'
      - .editorconfig
      - adrs/**
      - docs/**
      - examples/**
      - website/**
      - scripts/**
  pull_request: null
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 21
          check-latest: true
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      - name: Install the latest npm
        run: npm install -g npm
      - name: Install dependencies
        run: pnpm install
      - name: Run build
        run: pnpm run build
      - name: Run lint
        run: pnpm run lint
      - name: Publish
        run: |
          if git log -1 --pretty=%B | grep "^release: [0-9]\+\.[0-9]\+\.[0-9]\+$";
          then
            pnpm --filter "./packages/**" publish --provenance --access public
          elif git log -1 --pretty=%B | grep "^release: [0-9]\+\.[0-9]\+\.[0-9]\+-beta\.[0-9]\+$";
          then
            pnpm --filter "./packages/**" publish --provenance --access public --tag beta
          elif git log -1 --pretty=%B | grep "^release: [0-9]\+\.[0-9]\+\.[0-9]\+-next\.[0-9]\+$";
          then
            pnpm --filter "./packages/**" publish --provenance --access public --tag next
          else
            echo "Not a release, skipping publish"
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
